apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging-app
  template:
    metadata:
      labels:
        app: django-messaging-app
    spec:
      containers:
        - name: django-messaging-app
          image: your-dockerhub-username/django-messaging-app:latest  # Replace with your image
          ports:
            - containerPort: 8000  # Change if your app runs on a different port
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "your_project.settings"  # Adjust according to your settings
            - name: DATABASE_URL
              value: "your-database-url"  # If you have a database, adjust accordingly
---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-app
spec:
  type: ClusterIP
  selector:
    app: django-messaging-app
  ports:
    - protocol: TCP
      port: 8000  # The port that the service will expose
      targetPort: 8000  # The port on the container
