apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging-app-green
  template:
    metadata:
      labels:
        app: django-messaging-app-green
    spec:
      containers:
        - name: django-messaging-app
          image: your-dockerhub-username/django-messaging-app:green  # Update to your new image
          ports:
            - containerPort: 8000
