#!/bin/bash

# Deploy the blue version
echo "Deploying the blue version..."
kubectl apply -f messaging_app/blue_deployment.yaml

# Deploy the green version
echo "Deploying the green version..."
kubectl apply -f messaging_app/green_deployment.yaml

# Create or update the service to point to the green version
echo "Creating or updating the service..."
kubectl apply -f messaging_app/kubeservice.yaml

# Check logs for the new version
echo "Checking logs for the green version..."
kubectl logs -l app=django-messaging-app-green
